spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://10.2.6.31:3306/spring_bpa?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    parameters:
      ACTIVE_PROFILE: ${spring.profiles.active}
  application:
    name: ${SPRING_APP_NAME:bpa-app}
  main:
    banner-mode: console
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
bpa:
  file-path: ${FILE_UPLOAD_PATH:/app/test}
server:
  servlet:
    context-path: /realm
logging:
  level:
    com.example.bpa: info

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always